apiVersion: v1
kind: Service
metadata:
  name: docker-kubernetes-service
spec:
  type: ClusterIP
  selector:
    app: docker-kubernetes-example
  ports:
  - protocol: TCP
    port: 90
    targetPort: 9090
